name: Build, Test, and Publish

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --configuration Release --no-restore
    
    - name: Test
      run: dotnet test --configuration Release --no-build --verbosity normal --results-directory ${{ github.workspace }}/test-results/:/test-results --logger trx

    - name: Publish test results
      uses: EnricoMi/publish-unit-test-result-action@v2
      with:
          files: |
            ${{ github.workspace }}/test-results/**/*.trx

    - name: Get version
      if: github.event_name == 'push' && (github.ref != 'refs/heads/main' && github.ref != 'refs/heads/master')
      id: get_version
      uses: paulhatch/semantic-version@v6.0.1
      with:
        tag_prefix: "v"
        version_format: "${major}.${minor}.${patch}-prerelease-${{ env.BRANCH_NAME }}-${increment}"
        major_pattern: "(MAJOR)"
        minor_pattern: "(MINOR)"
        search_commit_body: true

    - name: Get version
      if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
      id: get_version
      uses: paulhatch/semantic-version@v6.0.1
      with:
        tag_prefix: "v"
        version_format: "${major}.${minor}.${patch}"
        major_pattern: "(MAJOR)"
        minor_pattern: "(MINOR)"
        search_commit_body: true
    
    - name: Pack NuGet package
      if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
      run: dotnet pack SqliteCache/SqliteCache.csproj -c Release -p:DebugSymbols=true -p:DebugType=embedded -p:Version=${{ steps.get_version.outputs.version }}
    
    - name: Publish to GitHub Packages
      run: |
        dotnet nuget push ./artifacts/*.nupkg \
          --source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" \
          --api-key ${{ secrets.GITHUB_TOKEN }} \
          --skip-duplicate
